### ISSUE TITLE
Tasks with today's date that are marked as completed still appears in the "Due Today" panel

### ISSUE THREAD

**Issue by CSmortal** [AY2021S2-CS2103T-W14-4/tp#145]
Marked the 3rd task as completed and expected it to disappear from the "Due Today" UI panel but it still stays there

![image](https://user-images.githubusercontent.com/67994626/113503131-6e03ab80-9562-11eb-9eba-4d5aefb23fed.png)

**Comment by noelmathewisaac** [comment]
This is expected behaviour. Due today will display all the tasks with the current days date regardless of status

**Comment by CSmortal** [comment]
But the user won't be interested in tasks to be done by today but are already completed. Isn't the "Due Today" panel meant for users to make a better decision on which task to do next? There is no point in keeping completed tasks that are due by today to be in that panel

**Comment by noelmathewisaac** [comment]
Changing this will require a lot of changes in the codebase especially in the implementation of the edit command. For now, we can consider renaming the panel to "Today's Tasks" and push the feature to post v1.4.
